CWR_AMBA_TLM2_BL=/net/software/r1/Linux/software/Synopsys_CoWare/N-2017.12/VPProducts/SLS/linux/IP_common/AMBA_TLM2_BL
CWR_ARM926EJS_TLM2_PSP=/net/software/r1/Linux/software/Synopsys_CoWare/N-2017.12/VPProducts/IP/ARM926EJS_TLM2_PSP
CWR_ARM_COPROC=/net/software/r1/Linux/software/Synopsys_CoWare/N-2017.12/VPProducts/IP/ARM_COPROC
CWR_GENERICIPLIB=/net/software/r1/Linux/software/Synopsys_CoWare/N-2017.12/VPProducts/IP/GenericIPlib
CWR_TLM2_BL=/net/software/r1/Linux/software/Synopsys_CoWare/N-2017.12/VPProducts/IP/TLM2_BL
