// File: mem_map.h - generated by CoWare Platform Creator.

#ifndef MEM_MAP_H
#define MEM_MAP_H

// Information for core HARDWARE.ARM
//  for memoryport IAHB
// 
#define HARDWARE_ARM_IAHB_HARDWARE_ROM_m_memory_base_address 0x0
#define HARDWARE_ARM_IAHB_HARDWARE_ROM_m_memory_size 0x10000
//  for memoryport DAHB
// 
#define HARDWARE_ARM_DAHB_HARDWARE_ROM_m_memory_base_address 0x0
#define HARDWARE_ARM_DAHB_HARDWARE_ROM_m_memory_size 0x10000
// 
#define HARDWARE_ARM_DAHB_HARDWARE_RAM_m_memory_base_address 0x4000000
#define HARDWARE_ARM_DAHB_HARDWARE_RAM_m_memory_size 0x10000
// 
#define HARDWARE_ARM_DAHB_HARDWARE_TERMINAL_m_regs_base_address 0x8000000
#define HARDWARE_ARM_DAHB_HARDWARE_TERMINAL_m_regs_size 0xc
// 
#define HARDWARE_ARM_DAHB_HARDWARE_i_counter_targetSocket_base_address 0x9000000
#define HARDWARE_ARM_DAHB_HARDWARE_i_counter_targetSocket_size 0x400
// 
#define HARDWARE_ARM_DAHB_HARDWARE_i_display_targetSocket_base_address 0xa000000
#define HARDWARE_ARM_DAHB_HARDWARE_i_display_targetSocket_size 0x100000
//  for memoryport ITCM_DATA
// 
#define HARDWARE_ARM_ITCM_DATA_HARDWARE_ITCM_DATA_base_address 0x0
#define HARDWARE_ARM_ITCM_DATA_HARDWARE_ITCM_DATA_size 0x100000
//  for memoryport DTCM_DATA
// 
#define HARDWARE_ARM_DTCM_DATA_HARDWARE_DTCM_DATA_base_address 0x0
#define HARDWARE_ARM_DTCM_DATA_HARDWARE_DTCM_DATA_size 0x100000


#endif /* MEM_MAP_H */
